### ISSUE TITLE
Difficulty Exporting .ply File from MVSplat Scenes

### ISSUE THREAD

**Issue by Vinay-constructn** [donydchen/mvsplat#20]
Hi, I am writing to bring to your attention an issue I encountered while attempting to export .ply files from scenes generated by MVSplat after running the Evaluation phase.

Background:
 I utilized the following inputs and steps:
 1. Inputs: 
      --Dataset: re10k 
      --Location: datasets/re10k/test 
      
  2. Output: 
  Scenes Generated after evolution  phase: test -> re10k List of scenes: [ 0c4c5d5f751aabf5  28e8300e004ab30b  57d25dafabb5a238  67a69088a2695987  a56ba2efb5e3fdd9... so on ]
  
  **Issue Details:** 
  
  After processing the Evaluation phase on the re10k dataset, I attempted to export .ply files from the generated scenes using the provided script:
  python -m src.paper.generate_point_cloud_figure_mvsplat \
 +experiment=re10k \
  checkpointing.load=checkpoints/re10k.ckpt \
  mode=test \
  dataset/view_sampler=evaluation
 
 I made a modification to load index.json in generate_point_cloud_figure_mvsplat.py as follows:
 
       with open("datasets/re10k/test/index.json") as f:
              test_cfgs = json.load(f)

However, upon running the script, I encountered errors.
![Screenshot 2024-04-19 163747](https://github.com/donydchen/mvsplat/assets/137394019/a4797dfd-aa56-4484-8246-c37dbe599206)

 Questions:
    1. How can I specify scenes as inputs in the script? 
    2. What steps are necessary to successfully export .ply files from the generated scenes after the Evaluation phase?
 
 I appreciate your assistance in resolving this issue. Please let me know if there are any further steps or information required from my end.
 
 Thank you

**Comment by donydchen** [comment]
Hi @Vinay-constructn, thanks for your interest in our work.

Sorry that the point cloud codes have not yet been properly cleaned, but it actually works out fine in our environment, as I have just tested. The command I used is as below:

```bash
python -m src.paper.generate_point_cloud_figure_mvsplat +experiment=re10k \
checkpointing.load=checkpoints/re10k.ckpt
```

No need to modify any part of the code. So, just load the original `"assets/evaluation_index_re10k.json"`. 

To specify the scene, update [this line](https://github.com/donydchen/mvsplat/blob/main/src/paper/generate_point_cloud_figure_mvsplat.py#L96). Note that the tested scene (i.e., "5ca0d8f0b24ae0aa") happens to be from the full dataset and does not exist in the tiny subset (I reckon that might be the reason why you tried to change the index file). But you can simply change it to another scene that exists in the tiny subset; that should also work. The meaning of each value in the above line can refer to [this line](https://github.com/donydchen/mvsplat/blob/main/src/paper/generate_point_cloud_figure_mvsplat.py#L137), but you might need to quickly go through the whole script to better understand how to tune the values. 

No further step is required; just run the above command, and the exported point cloud will be located at `point_clouds/re10k/[SCENE_NAME]/gaussians.ply`. You can then use any online 3D Gaussians viewer to view it, e.g., [3D Gaussian Splatting with Three.js](https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php?art=1&cu=0,0,1&cp=0,1,0&cla=1,0,0) (camera up should be set to "0,0,1").

**Comment by Vinay-constructn** [comment]
Hello, and thank you for your prompt response.

I appreciate the clarification regarding the specific scene ("5ca0d8f0b24ae0aa") and its origin from the complete dataset. However, I encountered difficulty locating this scene within the datasets provided in your drive repository. 

![Screenshot 2024-04-21 232914](https://github.com/donydchen/mvsplat/assets/137394019/e3979a4d-7ca9-41f4-8518-49d218f8e369)


Despite thorough searches across all available index.json files, I couldn't find it, except in assets/evaluation_index_re10k.json.

Following your instructions, I attempted to execute the provided command without any modifications:

python -m src.paper.generate_point_cloud_figure_mvsplat +experiment=re10k \
checkpointing.load=checkpoints/re10k.ckpt

Unfortunately, this resulted in an error, as depicted in the attached image.

![Screenshot 2024-04-21 233329](https://github.com/donydchen/mvsplat/assets/137394019/acee67fe-0461-41b9-bce5-e943e9733522)

**Moving forward, I have a few questions for clarification:**

1. Could you please specify where I can access the complete dataset?
2. Regarding the scene parameters you mentioned:
      For a scene like "5ca0d8f0b24ae0aa", where can I find the corresponding values for parameters such as scene, context 1, 
      context 2, far plane (e.g., 7, 113, 6.0, [110], 1.4, 19) for any particular scene?
3. In reference to your mention of converting downloaded versions of the Real Estate 10k and ACID datasets to your format 
    using scripts:
    Where can I find the metadata required for the conversion process, as indicated by INPUT_METADATA_DIR = 
    Path("/data/scene-rep/Real-Estate-10k/metadata/RealEstate10K") in convert.py?
    
 Your guidance and support in addressing these inquiries would be immensely appreciated. Thank you for your time and assistance.

**Comment by donydchen** [comment]
Hi @Vinay-constructn, no worries. Your questions are answered as below,

1. To access the complete dataset, you can send an email to the [pixelSplat](https://github.com/dcharatan/pixelsplat) group, indicating that you want to get the full versions of the processed RE10K and ACID datasets. Further instructions are detailed in the project [README](https://github.com/donydchen/mvsplat/?tab=readme-ov-file#realestate10k-and-acid).

2. The context views are normally obtained from the `assets/evaluation_index_re10k.json`. For other values, we manually choose them so as to get a better projected _2D_ figure for paper demonstration. But they are not so critical for exporting the 3D point cloud, since you can easily view the exported scenes from any angle with the 3DGS viewer.

3. The convert.py script is necessary _only if_ you opt to download the raw (unprocessed) RE10K dataset from [HERE](https://google.github.io/realestate10k/download.html). However, I strongly recommend you just contact the pixelSplat group via email to obtain the processed datasets, which can significantly save time and storage space.

**Comment by donydchen** [comment]
Hi @tanveer90, you may have mistakenly used the DTU dataset, which is for testing only.

You might need to double-check that you download the preprocessed RE10K subset from [here](https://drive.google.com/drive/folders/1joiezNCyQK2BvWMnfwHJpm2V77c7iYGe), following the instructions in the [README](https://github.com/donydchen/mvsplat?tab=readme-ov-file#realestate10k-and-acid).

**Comment by trungphien** [comment]
Hi, I just run this command that you mentioned above to export .ply file: 
```
python -m src.paper.generate_point_cloud_figure_mvsplat +experiment=re10k \
checkpointing.load=checkpoints/re10k.ckpt
```
But I get the following error. How can I solve it
![image](https://github.com/user-attachments/assets/d9d2ba3e-4b4e-4b3b-ae78-3ca1b3fac5d5)

**Comment by donydchen** [comment]
Hi @trungphien, this is not directly related to the export .ply function, but from the error log, it seems you might have forgotten to download the backbone pre-trained weight. As mentioned in the [README](https://github.com/donydchen/mvsplat?tab=readme-ov-file#training), kindly run 

```bash
# download the backbone pretrained weight from unimatch and save to 'checkpoints/'
wget 'https://s3.eu-central-1.amazonaws.com/avg-projects/unimatch/pretrained/gmdepth-scale1-resumeflowthings-scannet-5d9d7964.pth' -P checkpoints
```
