### ISSUE TITLE
What are the best practices for incorporating custom dataset inputs?

### ISSUE THREAD

**Issue by Harshitavardhani** [donydchen/mvsplat#21]
Hi @donydchen, kudos to your work. Your work MVSplat has my keen interest and I'm particularly interested in using it with custom datasets, but I'm having some trouble with a few things.

1.Do i have to upload custom dataset to the YouTube and use the URL, like in your dataset? Is there another approach I can take? If yes, could you please tell that approach?
2.How do you generate timestamps, camera poses, images, and keys for a particular video? 

Thank you in advance.

**Comment by donydchen** [comment]
Hi @Harshitavardhani, thanks for your interest in our work.

1. No. It is unnecessary to upload the custom data to YouTube, that is merely the way RealEstate10K provides its data. Our dataloader loads data from local storage. For building a customized dataloader, kindly refer to https://github.com/donydchen/mvsplat/issues/1

2. In this project, all datasets we use provide camera poses and extracted image frames. If you intend to work on your own video, you can check and follow how [RealEstate10K](https://tinghuiz.github.io/projects/mpi/) or [ACID](https://infinite-nature.github.io) preprocess their data.
