### ISSUE TITLE
Creating world-space covariance matrices

### ISSUE THREAD

**Issue by Shubhendu-Jena** [donydchen/mvsplat#26]
Hi, thanks for the great work. I was trying to understand your code, and I have doubts with the following operation.

        # Create world-space covariance matrices.
        covariances = build_covariance(scales, rotations)
        c2w_rotations = extrinsics[..., :3, :3]
        covariances = c2w_rotations @ covariances @ c2w_rotations.transpose(-1, -2)

Could you please clarify why this is being done? 

Thanks in advance

**Comment by donydchen** [comment]
Hi @Shubhendu-Jena, since our encoder predicts Gaussian parameters in camera space, these parameters must be transformed into world space before rendering. In particular, these operations here build the covariance matrix from the predicted scales and rotations and then transform it into world space for further rendering.

**Comment by Shubhendu-Jena** [comment]
Hi, thanks for the quick response. Why didn't you just multiply the rotation matrix with the c2w matrix in that case? Is it because converting it back to the quaternion format will cause ambiguity? I wanted to just use the scales and rotations and not the covariance matrix as input to the rasterizer, hence the question.

**Comment by donydchen** [comment]
I see. We use an off-the-shelf [rasterizer](https://github.com/dcharatan/diff-gaussian-rasterization-modified), which takes the world space covariance matrix as input, so we do need to do those operations to match its input.

**Comment by Shubhendu-Jena** [comment]
Got it. Thanks so much for the response.
