### ISSUE TITLE
Resolution Requirements

### ISSUE THREAD

**Issue by savvaki** [donydchen/mvsplat#34]
Thank you for the incredible work. I have 2 questions:

1. How can I test the models at a resolution different from 256x256? 
2. How would the latency of this approach change at higher resolutions?

Thank you for your time.

**Comment by donydchen** [comment]
Hi, @savvaki, thanks for your interest in our work.

1. You can change the testing resolution at https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/config/experiment/re10k.yaml#L38, or by appending an additional parameter when running the test command, e.g. `dataset.image_shape=[512,512]`.

2. Typically, higher resolution leads to longer testing time and more memory consumption, but we have yet to conduct a quantitative measurement in this regard. If you encounter out-of-memory issues when testing on higher resolution, you can tune some configurations to reduce the memory cost of our backbone. However, it might lead to suboptimal performance. For example, set `model.encoder.multiview_trans_attn_split=4` or `model.encoder.downscale_factor=8`. More details regarding these settings can be referred to our backbone module [UniMatch](https://github.com/autonomousvision/unimatch).

**Comment by savvaki** [comment]
Thank very much for your response! If there are any other questions I will open another issue.
