### ISSUE TITLE
How to generate `evaluation_index_re10k.json` and `evaluation_index_re10k_video.json`?

### ISSUE THREAD

**Issue by thucz** [donydchen/mvsplat#36]
I want to evaluate MvSplat on another dataset. I need to generate the evaluation index file. Could you tell me how to make it?

**Comment by donydchen** [comment]
Hi @thucz, thanks for your interest in our work.

You can generate `evaluation_index_re10k.json` by running:

```bash
python -m src.scripts.generate_evaluation_index \
data_loader.train.num_workers=0 \
data_loader.test.num_workers=0 \
data_loader.val.num_workers=0
```

By default, the generated index file will be saved to `outputs/evaluation_index_re10k/evaluation_index.json`. Then, you can generate the corresponding video index file by running:

```bash
python -m src.scripts.generate_video_evaluation_index \
--index_input=outputs/evaluation_index_re10k/evaluation_index.json \
--index_output=outputs/evaluation_index_re10k/evaluation_index_video.json
```

**Comment by wangdayan** [comment]
> Hi [@thucz](https://github.com/thucz), thanks for your interest in our work.
> 
> You can generate `evaluation_index_re10k.json` by running:
> 
> python -m src.scripts.generate_evaluation_index \
> data_loader.train.num_workers=0 \
> data_loader.test.num_workers=0 \
> data_loader.val.num_workers=0
> By default, the generated index file will be saved to `outputs/evaluation_index_re10k/evaluation_index.json`. Then, you can generate the corresponding video index file by running:
> 
> python -m src.scripts.generate_video_evaluation_index \
> --index_input=outputs/evaluation_index_re10k/evaluation_index.json \
> --index_output=outputs/evaluation_index_re10k/evaluation_index_video.json

Hello,
I noticed that in the mvsplat360 codebase, the generated evaluation_index.json always contains a fixed number of two views in the context field.

May I ask how to generate evaluation index files where the context contains multiple views (e.g., 4, 6, or 8)?
Specifically, which part of the code controls the number of context views during the generation of evaluation_index.json, and how can it be modified or configured to support a variable number of context views?

Thank you very much for your help.
