### ISSUE TITLE
Hi! How can I visualize the ply file with RGB colors?

### ISSUE THREAD

**Issue by thucz** [donydchen/mvsplat#39]
I cannot find out the entry to import the .ply file for Polycam. How did you make it?

**Comment by donydchen** [comment]
Hi @thucz, I remember there was a button on the Polycam homepage to upload the .ply file, but they seem to have removed that function.  

You can also try to visualize the ply file by using the [3D Gaussian Splatting with Three.js](https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php), note that you will need to set the camera up as `0,0,1` if you export the .ply file using our project.

**Comment by thucz** [comment]
Thanks a lot!

**Comment by thucz** [comment]
Can this website support precomputed RGB outputs instead of spherical harmonics?
