### ISSUE TITLE
Question about rendering depth from the predicted gaussians

### ISSUE THREAD

**Issue by fangchuan** [donydchen/mvsplat#40]
Thanks a lot for your awesome work!

I walk through your shared codes, it's well-structured and clear. But I have some question about the way your render depth map from gaussian splitting:
https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/src/model/decoder/cuda_splatting.py#L239-L251
https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/src/model/decoder/cuda_splatting.py#L264

It seems you use the gaussian kernels' `z` values as the initial color for rendering, it makes me feel confused as this is not normal method when we want to render depth from gaussian. I noticed you use the same way to render depth image in generate_point_cloud_figure_mvsplat.py, could you help me to understand the usage? @donydchen 

Thanks inn advance!

**Comment by donydchen** [comment]
Hi @fangchuan, thanks for your interest in our work.

Indeed, the way we render depth is hacky. The main reasons are 1) the depth map is mainly for visualization as a way to debug the model during training, so its accuracy is not so important in this project; 2) this project relies on an off-the-shelf [3DGS renderer](https://github.com/dcharatan/diff-gaussian-rasterization-modified), which does not support depth rendering by default.

If you want to obtain accurate depth visualization or even apply depth loss in training, I suggest replacing the rendering engine with https://github.com/Chrixtar/latent-gaussian-rasterization. It is also built on top of the original pixelSplat's renderer used by our project, thus it can be easily adopted. The key thing you will need to update is to change the output of the rasterizer from https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/src/model/decoder/cuda_splatting.py#L117-L124 to 
```python
image, feature_map, alpha_mask, depth_map, radii = rasterizer( ...
```

After that, you can visualize the depth using the rendered `depth_map`.

**Comment by fangchuan** [comment]
> Hi @fangchuan, thanks for your interest in our work.
> 
> Indeed, the way we render depth is hacky. The main reasons are 1) the visualization of depth map is mainly for debugging the model during training, so its accuracy is not so important in this project; 2) this project relies on an off-the-shelf [3DGS renderer](https://github.com/dcharatan/diff-gaussian-rasterization-modified), which does not support depth rendering by default.
> 
> If you want to obtain accurate depth visualization or even apply depth loss in training, I suggest replacing the rendering engine with https://github.com/Chrixtar/latent-gaussian-rasterization. It is also built on top of the original pixelSplat's renderer used by our project, thus it can be easily adopted. The key thing you will need to update is to change the output of the rasterizer from
> 
> https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/src/model/decoder/cuda_splatting.py#L117
> 
> to
> ```python
> image, feature_map, alpha_mask, depth_map, radii = rasterizer(
> ```
> 
> After that, you can visualize the depth using the rendered `depth_map`.

Thanks for your explanation, it addresses my conncerns.
