### ISSUE TITLE
About the interactive viewers

### ISSUE THREAD

**Issue by jjlinghu** [donydchen/mvsplat#43]
Hi! Thanks for your amazing work! 
Does MVSplat support interactive viewers such as the SIBR framework on Windows?
From the paper, we know that it can visualize MVSplat’s 3D Gaussians. Could you give me some guidance?
Thanks in advance!

**Comment by donydchen** [comment]
Hi @jjlinghu, we have not implemented any interactive viewers for this project.

As for visualizing the 3D Gaussians, you can start by extracting the point cloud (see instructions at https://github.com/donydchen/mvsplat/issues/20), then use any online 3DGS viewer to visualize it (see instructions at https://github.com/donydchen/mvsplat/issues/39)

**Comment by jjlinghu** [comment]
Thanks for your reply! I will try it.
