### ISSUE TITLE
Any suggestions about picking reference views?

### ISSUE THREAD

**Issue by Runyu-Zhou05** [donydchen/mvsplat#47]
Hi there, thanks a lot for your great work! Now I have my custom datasets and I want to use MVSplat to initialize a 3DGS model for further training. Do you have any suggestions about how to pick the reference views for each view, like the number of references views and the desired relative camera motion? Also, was the PLY exported by `src/paper/generate_point_cloud_figure_mvsplat.py` aggregated from all the depth maps?

Thank you so much!

**Comment by donydchen** [comment]
Hi @Runyu-Zhou05, thanks for your interest in our work.

You may consider starting with 2 or 3 reference views and ensuring enough overlap between the input reference views, e.g., more than 60% overlap. For more details about how the re10k input views are selected, kindly refer to https://github.com/donydchen/mvsplat/issues/36.

The exported PLY represents the 3D Gausssians of the whole scene, including depth information of all input views.
