### ISSUE TITLE
skipped bad example when using acid dataset

### ISSUE THREAD

**Issue by xingyoujun** [donydchen/mvsplat#49]
H, thank you for open source your great work!

I tried to train on the whole acid dataset(161G) but i got info like this:

![image](https://github.com/donydchen/mvsplat/assets/61579461/05dca4cb-80f4-4482-ac74-9c696834d6f7)

This happend frequently so I wonder i**f it's normal**. 
By the way, I got the full dataset from PixelSplat author and the files shuld be OK.

Thanks in advance!

**Comment by donydchen** [comment]
Hi @xingyoujun, thanks for your interest in our work.

Skipping images with undesired/invalid shapes is an expected behaviour, which is achieved by https://github.com/donydchen/mvsplat/blob/378ff818c0151719bbc052ac2797a2c769766320/src/dataset/dataset_re10k.py#L156-L164

**Comment by ChengLiDuoJi** [comment]
![屏幕截图 2024-10-27 215743](https://github.com/user-attachments/assets/d6d00d61-68a5-447e-a1bf-c0cf55d845aa)
I use acid too. I found that after 60k steps, it often skip bad samples. Should I stop training?
