### ISSUE TITLE
There was a problem during evaluation, rendering images were all black

### ISSUE THREAD

**Issue by yutmdfeng** [donydchen/mvsplat#60]
Executed command：CUDA_VISIBLE_DEVICES=2 python -m src.main +experiment=re10k checkpointing.load=checkpoints/re10k.ckpt mode=test dataset/view_sampler=evaluation test.compute_scores=true
----------------------------------------------------------------------------------------
Command line record：
Saving outputs to /workspace/mvsplat/outputs/2024-08-21/15-58-58.                root@1602ad04f0ea:/workspace/mvsplat/src/model/encoder# cd ..
rm: cannot remove 'outputs/local': No such file or directory                     
GPU available: True (cuda), used: True                                           .
TPU available: False, using: 0 TPU cores                                         
HPU available: False, using: 0 HPUs                                              
HPU available: False, using: 0 HPUs                                              
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]           
Loading model from: /opt/conda/envs/mvsplat/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth                                                               
Restoring states from the checkpoint path at checkpoints/re10k.ckpt              
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2]                                        
Loaded model weights from the checkpoint at checkpoints/re10k.ckpt               
Testing DataLoader 0:   0%|                               | 0/41 [00:00<?, ?it/s]
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]           
Loading model from: /opt/conda/envs/mvsplat/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth                                                               │
Testing DataLoader 0:  93%|_____________________ | 38/41 [00:10<00:00,  3.78it/s]
> /workspace/mvsplat/src/model/model_wrapper.py(249)on_test_end()                
-> name = get_cfg()["wandb"]["name"]                                             
(Pdb) c                                                                          
psnr 4.892539024353027                                                           
ssim 0.005905249947222489                                                        
lpips 0.7439133744490775                                                         
encoder: 33 calls, avg. 0.08216860077597878 seconds per call                     
decoder: 99 calls, avg. 0.0023896164364284943 seconds per call   
------------------------------------------------------------------------------------
For some reason, the progress bar stopped when it reached 38/41, but when I was debugging with pdb, I found that the save image was done, but when I went to output/test to view the rendered image, I found that all the images were completely black.
like this:
![000213](https://github.com/user-attachments/assets/c7d1b4d5-16c5-45ad-a087-792f24b314b9)
------------------------------------------------------------------------------------
I am a newcomer to this field, maybe the debug ability is still relatively limited. I tried to solve this problem for two days, really did not find a solution. I would appreciate it if team members and stakeholders could give me some Pointers. In addition, I think the setting and checkpoints should be no problem

**Comment by yutmdfeng** [comment]
Add: I ran this command on a separate GPU with about 24GB of memory (RTX 4090).

**Comment by donydchen** [comment]
Hi @yutmdfeng, I guess the problem is caused by the `diff-gaussian-rasterization-modified` submodule. As mentioned at https://github.com/donydchen/mvsplat/issues/15#issuecomment-2035830680, do ensure that it is installed via `pip install git+https://github.com/dcharatan/diff-gaussian-rasterization-modified` or `git clone --recursive`.

I believe the issue has been resolved according to your reply at https://github.com/donydchen/mvsplat/issues/16#issuecomment-2308347947. And regarding
> but in the reasoning process on re10k, I can still only go through 38/41steps.

The testing process is correct, and there is nothing to worry about. The reason is that the total length (41) is calculated based on a scene in the torch file (see https://github.com/donydchen/mvsplat/blob/main/src/dataset/dataset_re10k.py#L274), while the testing process will skip some scenes when they do not have enough frames (see https://github.com/donydchen/mvsplat/blob/main/src/dataset/dataset_re10k.py#L138). In other words, some scenes in the test set are not evaluated due to the experiment settings.

**Comment by yutmdfeng** [comment]
Thank you for your reply!Although I have solved the problem of the picture being all black, but if it wasn't for your reply I would have been confused with the problem of the progress bar!

**Comment by siyanhu** [comment]
Hi yutmdfeng, can I ask how you solve the problem? I actually tried installing diff-gaussian-rasterization-modified multiple times and it didn't pop up any errors during pip install. however I got rendering image all black as you mentioned firstly.

**Comment by siyanhu** [comment]
> Thank you for your reply!Although I have solved the problem of the picture being all black, but if it wasn't for your reply I would have been confused with the problem of the progress bar!

Hi yutmdfeng, can I ask how you solve the problem? I actually tried installing diff-gaussian-rasterization-modified multiple times and it didn't pop up any errors during pip install. however I got rendering image all black as you mentioned firstly.

**Comment by yutmdfeng** [comment]
@siyanhu Use the command "git clone https://github.com/dcharatan/diff-gaussian-rasterization-modified.git --recursive" Get the ff-Gaussian-rasterization-modified and some subsets of it, and then compile.

**Comment by siyanhu** [comment]
> @siyanhu Use the command "git clone https://github.com/dcharatan/diff-gaussian-rasterization-modified.git --recursive" Get the ff-Gaussian-rasterization-modified and some subsets of it, and then compile with"python setup.py build python setup.py install"

Hi thanks for your reply. I actually thought it could be the diffusion rasterisation error actually. I've tried recursive clone and it doesn't work at all... anyway, I tried with another card 3090 and it work fine haha. thanks for the reply!

**Comment by siyanhu** [comment]
ok I think this 4090 related issue could be solved by changing glm@5c46b9c to glm version 1.0.0.

**Comment by ttt-y** [comment]
> > > > [@siyanhu](https://github.com/siyanhu) Use the command "git clone https://github.com/dcharatan/diff-gaussian-rasterization-modified.git --recursive" Get the ff-Gaussian-rasterization-modified and some subsets of it, and then compile with"python setup.py build python setup.py install"
> > > 
> > > 
> > > Hi thanks for your reply. I actually thought it could be the diffusion rasterisation error actually. I've tried recursive clone, as well as setup.py installation with python build, and it doesn't work at all... anyway, I got it running successfully on another 3090. thank you for the tips!!
> > 
> > 
> > Hi, I meet the same problem too. I just use the 'pip install -r requirements.txt' command to install the diff-gaussian-rasterization-modified submodule. While in the requirements it is 'git+https://github.com/dcharatan/diff-gaussian-rasterization-modified'. I don't know where the problem is. If I uninstall it and reinstall with 'git clone https://github.com/dcharatan/diff-gaussian-rasterization-modified.git --recursive', will it work differently? And I also want to know how do you solve the problem? How do you change the glm version? Thanks a lot!!!
> 
> try other commits of the **glm** repo in "https://github.com/dcharatan/diff-gaussian-rasterization-modified"

Thanks for your reply!!! I've gotten this package
