### ISSUE TITLE
What is context and target images in index.json

### ISSUE THREAD

**Issue by ronly2460** [donydchen/mvsplat#70]
Thank you for amazing work!

What are they?

**Comment by donydchen** [comment]
Hi, @ronly2460, thanks for your appreciation.

MVSplat tackles the [novel view synthesis](https://en.wikipedia.org/wiki/View_synthesis) task. Hence, context images refer to the input/observed views, while target images refer to the target/unobserved views. And the `index.json` contains their corresponding index.

For details about how to create these index files, kindly check https://github.com/donydchen/mvsplat/issues/36.
