### ISSUE TITLE
The formula for calculating the 2D correspondence in depth matching is inconsistent with the code

### ISSUE THREAD

**Issue by ryankamanri** [donydchen/mvsplat#76]
The 2D correspondence formula for calculating the two images given in the UniMatch is like this:
![image](https://github.com/user-attachments/assets/a53407be-d011-485b-ac02-058c4e4e7c9f)
where the process of multiplying different depth planes is done before calculating the relative pose, but in the function ` warp_with_pose_depth_candidates`:
``` py
 points = torch.bmm(pose[:, :3, :3], points).unsqueeze(2).repeat(
            1, 1, d, 1) * depth.view(b, 1, d, h * w)  # [B, 3, D, H*W]
 points = points + pose[:, :3, -1:].unsqueeze(-1)  # [B, 3, D, H*W]
```
it seems to multiply the 2D homogeneous coordinates by the rotation matrix first and then by different depth planes. Is this a problem?

**Comment by JianxiangL** [comment]
"I believe they are mathematically equivalent."
