### ISSUE TITLE
Relationship between number of cost volumes and gaussians

### ISSUE THREAD

**Issue by Beastmaster** [donydchen/mvsplat#77]
Hi, It's a very impressive work!
I'm confused about number of cost volumes and number of gaussians. As stated in the paper, K const volumes for K input views are constructed to predict K depth maps. For each cost volume, (H/s)*(W/s) depth values are acquired, these depth values are unprojected to 3d point cloud. Does that mean K point clouds are acquired from K cost volumes? If so, how do you merge all of point clouds (gaussian centers)?

Best,

**Comment by donydchen** [comment]
Hey @Beastmaster, thanks for your appreciation.

Your understanding is correct, there are K point clouds predicted for K input views (or cost volumes). We did not apply any merging operations in the point clouds. Instead, we simply concatenate these point clouds and rely on the rasterisation operation to "merge" them. In other words, one 2D pixel can come from multiple 3D Gaussians, which are weighted by the corresponding predicted opacity.

If you are interested in merging the point clouds, you might want to check out [FreeSplat](https://github.com/wangys16/FreeSplat) or [Gaussian Graph Network](https://openreview.net/forum?id=2dfBpyqh0A), which both verified that merging the per-view 3D Gaussians can help improve the visual quality of MVSplat.

**Comment by YuhsiHu** [comment]
Hi, thank you for your great work! 

About point cloud fusion, where do you concatenate multiple point clouds generated from K depth maps in the code? Does this mean MVSplat can obtain a final point cloud and render an image from a novel view?
