### ISSUE TITLE
W2C and extrinsics

### ISSUE THREAD

**Issue by haowang020110** [donydchen/mvsplat#81]
Dear author 
Sorry I have a name problem
It seemed that the normal conception of the camera extrinsics is w2c matrix.
However you made extrinsics=c2w, can you tell me the reason?
Sorry again for my poor knowledge.
https://github.com/donydchen/mvsplat/blob/ef976a166da31e8392f2e5bee49bf66785e381e8/src/dataset/dataset_re10k.py#L224-L226

**Comment by donydchen** [comment]
Hi, @haowang020110, there is no specific reason for using c2w or w2c. The main reason might be the encoder involves some operations that are easier to start from camera space, e.g., the wrapping operation (#80), and the encoder predicts 3D Gaussians in camera space, which is then transformed into world space. Hence, it seems more convenient to use c2w in this project.

**Comment by haowang020110** [comment]
Thanks a lot!
