### ISSUE TITLE
Question about Scannet Dataset Training Results

### ISSUE THREAD

**Issue by ShengYu724** [donydchen/mvsplat#85]
Thank you for your excellent work!

I am trying to implement your method on a different dataset, like ScanNet. However, I am encountering issues where the _**loss does not converge**_ even after 20,000 iterations,**_The rendered results are either completely blank or extremely blurry_**, as shown below, left is rendering, right is GT.
![output_600](https://github.com/user-attachments/assets/e7995f21-9847-4c36-9cc0-c85c128966f4)

I have converted the data formate to re10k, as specified in your code. 
The camera pose is _**c2w**_ in OpenCV format, which project points in camera coordinate to word coordinate, and the _**intrinsics have been normalized**_, the img size is (640,360). 
The **_sample distance of context_** is much small than re10k, which is _**min=4 max=8 for initial**_, because I noticed that the view changes in ScanNet are larger than in RE10K.
The **_(near,far) is set to (1,50)_**.

Although I modified the CUDA code for Gaussian splatting, the results from **_src/scripts/test_splatter.py_**appear correct. I did not change the color rendering portion of the CUDA code.

Could this issue be due to the need for _**more iterations to train**_? Training for 300k iterations is little challenging for 8×3090 GPUs. 
I would greatly appreciate any advice or insights you can provide!
Thank you!

**Comment by donydchen** [comment]
Hi @ShengYu724, thanks for your appreciation.

You might want to look into the implementation of [FreeSplat](https://github.com/wangys16/FreeSplat), which uses the same experiment settings as our MVSplat. According to the results reported in FreeSplat, MVSplat should perform reasonably well in the ScanNet dataset. 

Hope it helps. Cheers.

**Comment by ShengYu724** [comment]
> Hi @ShengYu724, thanks for your appreciation.
> 
> You might want to look into the implementation of [FreeSplat](https://github.com/wangys16/FreeSplat), which uses the same experiment settings as our MVSplat. According to the results reported in FreeSplat, MVSplat should perform reasonably well in the ScanNet dataset.
> 
> Hope it helps. Cheers.

Thanks for your advice! I'll check FreeSplat!

**Comment by ShengYu724** [comment]
> [@ShengYu724](https://github.com/ShengYu724) Have you solved the problem? I am trying to evaluate the model on ScanNet++ and encounter the similar issue, as shown below, left is rendering, right is GT.
> 
> ![Image](https://github.com/user-attachments/assets/f1bdf8fc-5a74-438a-8704-f0377db0654b)

The issue is caused by an incompatible version of glm. You wouldn't encounter this problem if you followed the installation steps provided in the README.

**Comment by deriveFromC** [comment]
> > [@ShengYu724](https://github.com/ShengYu724) Have you solved the problem? I am trying to evaluate the model on ScanNet++ and encounter the similar issue, as shown below, left is rendering, right is GT.
> > ![Image](https://github.com/user-attachments/assets/f1bdf8fc-5a74-438a-8704-f0377db0654b)
> 
> The issue is caused by an incompatible version of glm. You wouldn't encounter this problem if you followed the installation steps provided in the README.

Thank you for your response. Could you please share more details about how you processed the camera parameters? I might have made some mistakes in these steps. Specifically, could you explain how you converted the dataset's camera poses to the OpenCV format, and how you normalized the camera intrinsics? Additionally, did you perform any other preprocessing on the ScanNet dataset besides these steps?

I truly appreciate you taking the time to share your expertise. Your guidance would be extremely helpful for my work.

**Comment by ShengYu724** [comment]
The camera pose is already in OpenCV format and represents the transformation from camera to world coordinates, which differs from the convention used in the Re10k dataset. Intrinsics normalization is done by dividing the first row by the image width and the second row by the image height.

**Comment by ShengYu724** [comment]
> > > [@ShengYu724](https://github.com/ShengYu724) Have you solved the problem? I am trying to evaluate the model on ScanNet++ and encounter the similar issue, as shown below, left is rendering, right is GT.
> > > ![Image](https://github.com/user-attachments/assets/f1bdf8fc-5a74-438a-8704-f0377db0654b)
> > 
> > 
> > The issue is caused by an incompatible version of glm. You wouldn't encounter this problem if you followed the installation steps provided in the README.
> 
> Thank you for your response. Could you please share more details about how you processed the camera parameters? I might have made some mistakes in these steps. Specifically, could you explain how you converted the dataset's camera poses to the OpenCV format, and how you normalized the camera intrinsics? Additionally, did you perform any other preprocessing on the ScanNet dataset besides these steps?
> 
> I truly appreciate you taking the time to share your expertise. Your guidance would be extremely helpful for my work.

The camera pose is already in OpenCV format and represents the transformation from camera to world coordinates, which differs from the convention used in the Re10k dataset. Intrinsics normalization is done by dividing the first row by the image width and the second row by the image height.

**Comment by deriveFromC** [comment]
> > > > [@ShengYu724](https://github.com/ShengYu724) Have you solved the problem? I am trying to evaluate the model on ScanNet++ and encounter the similar issue, as shown below, left is rendering, right is GT.
> > > > ![Image](https://github.com/user-attachments/assets/f1bdf8fc-5a74-438a-8704-f0377db0654b)
> > > 
> > > 
> > > The issue is caused by an incompatible version of glm. You wouldn't encounter this problem if you followed the installation steps provided in the README.
> > 
> > 
> > Thank you for your response. Could you please share more details about how you processed the camera parameters? I might have made some mistakes in these steps. Specifically, could you explain how you converted the dataset's camera poses to the OpenCV format, and how you normalized the camera intrinsics? Additionally, did you perform any other preprocessing on the ScanNet dataset besides these steps?
> > I truly appreciate you taking the time to share your expertise. Your guidance would be extremely helpful for my work.
> 
> The camera pose is already in OpenCV format and represents the transformation from camera to world coordinates, which differs from the convention used in the Re10k dataset. Intrinsics normalization is done by dividing the first row by the image width and the second row by the image height.

Thank you for your help. I'll check my code following your guidance
