### ISSUE TITLE
Questions regarding the dataset

### ISSUE THREAD

**Issue by jjkkjok** [donydchen/mvsplat#86]
Hello, author. First of all, please allow me to express my admiration for the outstanding work accomplished by your team. After reading your paper, I would like to try training using your complete dataset. Could you please provide me with the full data? Thank you very much, and wish you a happy life.

**Comment by donydchen** [comment]
Hi @jjkkjok, thanks for your appreciation. Please follow the instructions in [README](https://github.com/donydchen/mvsplat?tab=readme-ov-file#acquiring-datasets) to obtain the full training datasets. Cheers.
