### ISSUE TITLE
3D object reconstruction

### ISSUE THREAD

**Issue by Dumeowmeow** [donydchen/mvsplat#87]
Hi, thank you for your great work! I was curious to see if this method could be used to reconstruct 3D objects from sparse viewpoints (i.e. 6 different viewpoints) instead of 3D scenes?

**Comment by donydchen** [comment]
Hi, @Dumeowmeow, thanks for your appreciation.

MVSplat is mainly designed and trained on scene-level datasets (with background, not specifically orbiting one object), and I'm not sure how well it will perform on object-level data. One way is to retrain MVSplat on object-level datasets such as CO3D. You may find more references about loading and training CO3D data in [latentSplat](https://github.com/Chrixtar/latentsplat), which shares the same code base as ours.

**Comment by Dumeowmeow** [comment]
> Hi, @Dumeowmeow, thanks for your appreciation.
> 
> MVSplat is mainly designed and trained on scene-level datasets (with background, not specifically orbiting one object), and I'm not sure how well it will perform on object-level data. One way is to retrain MVSplat on object-level datasets such as CO3D. You may find more references about loading and training CO3D data in [latentSplat](https://github.com/Chrixtar/latentsplat), which shares the same code base as ours.

Thank you for your reply.Is this paper's approach to train a single model with different scenarios? Then we can use this model to make predictions for a new scene, for example, given two images of a new scene, and the model can reconstruct the complete scene. Do I understand correctly? :）

**Comment by donydchen** [comment]
Correct. Both MVSplat and latentSplat are feed-forward (aka generalizable) approaches, which are trained on thousands of scenes and can be directly tested on new scenes with a single forward pass.
