### ISSUE TITLE
Question about Cost volume construction

### ISSUE THREAD

**Issue by 3Der1999** [donydchen/mvsplat#9]
Hello, I don't understand the `inverse depth domain` and the specific operations of warp. I can't find explanations for the `inverse depth domain` online. 
Can you provide some information about them? Thanks!
![image](https://github.com/donydchen/mvsplat/assets/158052825/569c9bd5-3dbb-4dda-a1da-2b6817c7c186)

**Comment by donydchen** [comment]
It means that we sample the candidate depth planes uniformly in the inverse depth (_i.e._, $1/d$) space. The implementation detail is [HERE]( https://github.com/donydchen/mvsplat/blob/main/src/model/encoder/costvolume/depth_predictor_multiview.py#L115-L121).

This is a general approach in multi-view stereo. By sampling points in the inverse depth space, when we project these points back to the 2D image spaces, they will distribute more uniformly along the epipolar line. The image below (from [this paper](https://www.researchgate.net/publication/361412909_Learning_Inverse_Depth_Regression_for_Pixelwise_Visibility-Aware_Multi-View_Stereo_Networks)) provides a better illustration. 

![Illustration-of-depth-sampling-and-inverse-depth-sampling-a-Depth-sampling-Depth](https://github.com/donydchen/mvsplat/assets/5866866/60c69b39-c04b-4b4c-a4e3-a7e15d068f9f)

**Comment by Time-Lord12th** [comment]
Thanks for your detailed explanation, it really helps!
